name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd simple_devops_project
            git pull
            sudo docker build -t my-flask-app .
            sudo docker stop flask || true
            sudo docker rm flask || true
            sudo docker run -d \
              --name flask \
              -p 5000:5000 \
              -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
              -e UNSPLASH_KEY="${{ secrets.UNSPLASH_KEY }}" \
              dinner-decider
